-- Auto-generated by scrape_studios.py
-- 2026-05-20T05:27:54.814864+00:00

CREATE TABLE IF NOT EXISTS studios (
  id           SERIAL PRIMARY KEY,
  source       TEXT NOT NULL,
  source_id    TEXT,
  name         TEXT NOT NULL,
  category     TEXT,
  phone        TEXT,
  address      TEXT,
  road_address TEXT,
  lng          DOUBLE PRECISION,
  lat          DOUBLE PRECISION,
  place_url    TEXT,
  crawled_at   TIMESTAMPTZ,
  UNIQUE (source, source_id)
);
