-- Auto-generated by scripts/scrape_instructors.py
-- 2026-05-19T21:23:53.645150+00:00
--
-- Run after V4__add_instructors.sql migration.

INSERT INTO instructors (
    instructor_id, full_name, bio, certification_level, yoga_alliance_id,
    fyt_certified, lineage_school, lineage_depth, instagram_handle,
    instagram_followers, instagram_url, website_url,
    avg_rating, review_count, instructor_trust_score,
    city, country, data_source, scraped_at
) VALUES
    ('', '베파요가스쿨', NULL, NULL, NULL, FALSE, NULL, 0, NULL, NULL, NULL, NULL, NULL, 0, 0.0, '서울', 'KR', 'naver_local', '2026-05-19T21:23:06.730496+00:00'),
    ('amp', '아힘사 요가 &amp; 명상', NULL, NULL, NULL, FALSE, NULL, 0, NULL, NULL, NULL, NULL, NULL, 0, 0.0, '서울', 'KR', 'naver_local', '2026-05-19T21:23:06.730524+00:00'),
    ('ch', 'CH요가구루쿨', NULL, NULL, NULL, FALSE, NULL, 0, NULL, NULL, NULL, NULL, NULL, 0, 0.0, '울산', 'KR', 'naver_local', '2026-05-19T21:23:27.692334+00:00'),
    ('h', 'H요가 수지점', NULL, NULL, NULL, FALSE, NULL, 0, NULL, NULL, NULL, NULL, NULL, 0, 0.0, '용인', 'KR', 'naver_local', '2026-05-19T21:23:36.372016+00:00'),
    ('k', 'K요가지도자교육원', NULL, NULL, NULL, FALSE, NULL, 0, NULL, NULL, NULL, NULL, NULL, 0, 0.0, '안양', 'KR', 'naver_local', '2026-05-19T21:23:50.738534+00:00');