-- Auto-generated by scrape_associations.py
-- 2026-05-22T12:59:23.912866+00:00

CREATE TABLE IF NOT EXISTS associations (
  id           SERIAL PRIMARY KEY,
  source       TEXT NOT NULL,
  type         TEXT,
  name         TEXT NOT NULL,
  location     TEXT,
  cert_level   TEXT,
  country      CHAR(2),
  website      TEXT,
  member_count INTEGER,
  crawled_at   TIMESTAMPTZ,
  UNIQUE (source, name)
);

INSERT INTO associations (source,type,name,location,cert_level,country,website,member_count,crawled_at) VALUES ('static','national_federation','대한요가회','Seoul','국가공인','KR','http://www.koreayoga.or.kr',NULL,'2026-05-22T12:59:18.948902+00:00') ON CONFLICT (source,name) DO UPDATE SET website=EXCLUDED.website, crawled_at=EXCLUDED.crawled_at;
INSERT INTO associations (source,type,name,location,cert_level,country,website,member_count,crawled_at) VALUES ('static','national_association','한국요가협회','Seoul','민간','KR','https://www.koreayogaassociation.com',NULL,'2026-05-22T12:59:18.948902+00:00') ON CONFLICT (source,name) DO UPDATE SET website=EXCLUDED.website, crawled_at=EXCLUDED.crawled_at;
INSERT INTO associations (source,type,name,location,cert_level,country,website,member_count,crawled_at) VALUES ('static','international_alliance','Yoga Alliance (International)','USA','RYT-200/500/E-RYT','US','https://www.yogaalliance.org',NULL,'2026-05-22T12:59:18.948902+00:00') ON CONFLICT (source,name) DO UPDATE SET website=EXCLUDED.website, crawled_at=EXCLUDED.crawled_at;
INSERT INTO associations (source,type,name,location,cert_level,country,website,member_count,crawled_at) VALUES ('static','national_federation','생활체육요가연합회','Seoul','생활체육','KR',NULL,NULL,'2026-05-22T12:59:18.948902+00:00') ON CONFLICT (source,name) DO UPDATE SET website=EXCLUDED.website, crawled_at=EXCLUDED.crawled_at;
INSERT INTO associations (source,type,name,location,cert_level,country,website,member_count,crawled_at) VALUES ('static','national_association','한국아쉬탕가요가협회 (KAYA)','Seoul','아쉬탕가','KR',NULL,NULL,'2026-05-22T12:59:18.948902+00:00') ON CONFLICT (source,name) DO UPDATE SET website=EXCLUDED.website, crawled_at=EXCLUDED.crawled_at;
INSERT INTO associations (source,type,name,location,cert_level,country,website,member_count,crawled_at) VALUES ('static','international_alliance','Iyengar Yoga Association of Korea','Seoul','Iyengar','KR',NULL,NULL,'2026-05-22T12:59:18.948902+00:00') ON CONFLICT (source,name) DO UPDATE SET website=EXCLUDED.website, crawled_at=EXCLUDED.crawled_at;
INSERT INTO associations (source,type,name,location,cert_level,country,website,member_count,crawled_at) VALUES ('static','certification_body','YACEP (Yoga Alliance Continuing Education Provider)','USA','YACEP','US','https://www.yogaalliance.org/yacep',NULL,'2026-05-22T12:59:18.948902+00:00') ON CONFLICT (source,name) DO UPDATE SET website=EXCLUDED.website, crawled_at=EXCLUDED.crawled_at;